-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [jobq]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace jobq

/-- [jobq::queue::MAX_ATTEMPTS]
    Source: 'src/queue.rs', lines 9:0-9:32
    Visibility: public -/
@[global_simps, irreducible] def queue.MAX_ATTEMPTS : Std.U32 := 3#u32

/-- [jobq::queue::QueueError]
    Source: 'src/queue.rs', lines 12:0-19:1
    Visibility: public -/
@[discriminant isize]
inductive queue.QueueError where
| Full : queue.QueueError
| NotStartable : queue.QueueError
| NotRunning : queue.QueueError

/-- [jobq::queue::{core::fmt::Debug for jobq::queue::QueueError}::fmt]:
    Source: 'src/queue.rs', lines 11:9-11:14
    Visibility: public -/
def queue.QueueError.Insts.CoreFmtDebug.fmt
  (self : queue.QueueError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | queue.QueueError.Full => core.fmt.Formatter.write_str f (toStr "Full")
  | queue.QueueError.NotStartable =>
    core.fmt.Formatter.write_str f (toStr "NotStartable")
  | queue.QueueError.NotRunning =>
    core.fmt.Formatter.write_str f (toStr "NotRunning")

/-- Trait implementation: [jobq::queue::{core::fmt::Debug for jobq::queue::QueueError}]
    Source: 'src/queue.rs', lines 11:9-11:14 -/
@[reducible]
def queue.QueueError.Insts.CoreFmtDebug : core.fmt.Debug queue.QueueError := {
  fmt := queue.QueueError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [jobq::queue::{core::marker::StructuralPartialEq for jobq::queue::QueueError}]
    Source: 'src/queue.rs', lines 11:16-11:25 -/
@[reducible]
def queue.QueueError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq queue.QueueError := {
}

/-- [jobq::queue::{core::cmp::PartialEq<jobq::queue::QueueError> for jobq::queue::QueueError}::eq]:
    Source: 'src/queue.rs', lines 11:16-11:25
    Visibility: public -/
def queue.QueueError.Insts.CoreCmpPartialEqQueueError.eq
  (self : queue.QueueError) (other : queue.QueueError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [jobq::queue::{core::cmp::PartialEq<jobq::queue::QueueError> for jobq::queue::QueueError}]
    Source: 'src/queue.rs', lines 11:16-11:25 -/
@[reducible]
def queue.QueueError.Insts.CoreCmpPartialEqQueueError : core.cmp.PartialEq
  queue.QueueError queue.QueueError := {
  eq := queue.QueueError.Insts.CoreCmpPartialEqQueueError.eq
}

/-- [jobq::queue::{core::cmp::Eq for jobq::queue::QueueError}::assert_receiver_is_total_eq]:
    Source: 'src/queue.rs', lines 11:27-11:29
    Visibility: public -/
def queue.QueueError.Insts.CoreCmpEq.assert_receiver_is_total_eq
  (self : queue.QueueError) : Result Unit := do
  ok ()

/-- Trait implementation: [jobq::queue::{core::cmp::Eq for jobq::queue::QueueError}]
    Source: 'src/queue.rs', lines 11:27-11:29 -/
@[reducible]
def queue.QueueError.Insts.CoreCmpEq : core.cmp.Eq queue.QueueError := {
  partialEqInst := queue.QueueError.Insts.CoreCmpPartialEqQueueError
  assert_receiver_is_total_eq :=
    queue.QueueError.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/-- [jobq::queue::FailOutcome]
    Source: 'src/queue.rs', lines 23:0-28:1
    Visibility: public -/
@[discriminant isize]
inductive queue.FailOutcome where
| Retrying : queue.FailOutcome
| Exhausted : queue.FailOutcome

/-- [jobq::queue::{core::fmt::Debug for jobq::queue::FailOutcome}::fmt]:
    Source: 'src/queue.rs', lines 22:9-22:14
    Visibility: public -/
def queue.FailOutcome.Insts.CoreFmtDebug.fmt
  (self : queue.FailOutcome) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | queue.FailOutcome.Retrying =>
    core.fmt.Formatter.write_str f (toStr "Retrying")
  | queue.FailOutcome.Exhausted =>
    core.fmt.Formatter.write_str f (toStr "Exhausted")

/-- Trait implementation: [jobq::queue::{core::fmt::Debug for jobq::queue::FailOutcome}]
    Source: 'src/queue.rs', lines 22:9-22:14 -/
@[reducible]
def queue.FailOutcome.Insts.CoreFmtDebug : core.fmt.Debug queue.FailOutcome
  := {
  fmt := queue.FailOutcome.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [jobq::queue::{core::marker::StructuralPartialEq for jobq::queue::FailOutcome}]
    Source: 'src/queue.rs', lines 22:16-22:25 -/
@[reducible]
def queue.FailOutcome.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq queue.FailOutcome := {
}

/-- [jobq::queue::{core::cmp::PartialEq<jobq::queue::FailOutcome> for jobq::queue::FailOutcome}::eq]:
    Source: 'src/queue.rs', lines 22:16-22:25
    Visibility: public -/
def queue.FailOutcome.Insts.CoreCmpPartialEqFailOutcome.eq
  (self : queue.FailOutcome) (other : queue.FailOutcome) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [jobq::queue::{core::cmp::PartialEq<jobq::queue::FailOutcome> for jobq::queue::FailOutcome}]
    Source: 'src/queue.rs', lines 22:16-22:25 -/
@[reducible]
def queue.FailOutcome.Insts.CoreCmpPartialEqFailOutcome : core.cmp.PartialEq
  queue.FailOutcome queue.FailOutcome := {
  eq := queue.FailOutcome.Insts.CoreCmpPartialEqFailOutcome.eq
}

/-- [jobq::queue::{core::cmp::Eq for jobq::queue::FailOutcome}::assert_receiver_is_total_eq]:
    Source: 'src/queue.rs', lines 22:27-22:29
    Visibility: public -/
def queue.FailOutcome.Insts.CoreCmpEq.assert_receiver_is_total_eq
  (self : queue.FailOutcome) : Result Unit := do
  ok ()

/-- Trait implementation: [jobq::queue::{core::cmp::Eq for jobq::queue::FailOutcome}]
    Source: 'src/queue.rs', lines 22:27-22:29 -/
@[reducible]
def queue.FailOutcome.Insts.CoreCmpEq : core.cmp.Eq queue.FailOutcome := {
  partialEqInst := queue.FailOutcome.Insts.CoreCmpPartialEqFailOutcome
  assert_receiver_is_total_eq :=
    queue.FailOutcome.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/-- [jobq::queue::JobQueue]
    Source: 'src/queue.rs', lines 32:0-40:1
    Visibility: public -/
structure queue.JobQueue where
  capacity : Std.U32
  queued : Std.U32
  running : Bool
  attempts : Std.U32
  done : Std.U32
  failed : Std.U32
  submitted : Std.U32

/-- [jobq::queue::{core::fmt::Debug for jobq::queue::JobQueue}::fmt]:
    Source: 'src/queue.rs', lines 31:9-31:14
    Visibility: public -/
def queue.JobQueue.Insts.CoreFmtDebug.fmt
  (self : queue.JobQueue) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU32 self.capacity
  let dyn1 := Dyn.mk _ core.fmt.DebugU32 self.queued
  let dyn2 := Dyn.mk _ core.fmt.DebugBool self.running
  let dyn3 := Dyn.mk _ core.fmt.DebugU32 self.attempts
  let dyn4 := Dyn.mk _ core.fmt.DebugU32 self.done
  let dyn5 := Dyn.mk _ core.fmt.DebugU32 self.failed
  let dyn6 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU32) self.submitted
  let values :=
    Array.to_slice
      (Array.make 7#usize [ dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6 ])
  let s ←
    lift (Array.to_slice
      (Array.make 7#usize [
        toStr "capacity", toStr "queued", toStr "running", toStr "attempts",
        toStr "done", toStr "failed", toStr "submitted"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "JobQueue") s values

/-- Trait implementation: [jobq::queue::{core::fmt::Debug for jobq::queue::JobQueue}]
    Source: 'src/queue.rs', lines 31:9-31:14 -/
@[reducible]
def queue.JobQueue.Insts.CoreFmtDebug : core.fmt.Debug queue.JobQueue := {
  fmt := queue.JobQueue.Insts.CoreFmtDebug.fmt
}

/-- [jobq::queue::{jobq::queue::JobQueue}::new]:
    Source: 'src/queue.rs', lines 43:4-53:5
    Visibility: public -/
def queue.JobQueue.new (capacity : Std.U32) : Result queue.JobQueue := do
  ok
    {
      capacity,
      queued := 0#u32,
      running := false,
      attempts := 0#u32,
      done := 0#u32,
      failed := 0#u32,
      submitted := 0#u32
    }

/-- [jobq::queue::{jobq::queue::JobQueue}::submit]:
    Source: 'src/queue.rs', lines 56:4-63:5
    Visibility: public -/
def queue.JobQueue.submit
  (self : queue.JobQueue) :
  Result ((core.result.Result Unit queue.QueueError) × queue.JobQueue)
  := do
  if self.queued >= self.capacity
  then ok (core.result.Result.Err queue.QueueError.Full, self)
  else
    let i ← self.queued + 1#u32
    let i1 ← self.submitted + 1#u32
    ok (core.result.Result.Ok (), { self with queued := i, submitted := i1 })

/-- [jobq::queue::{jobq::queue::JobQueue}::start]:
    Source: 'src/queue.rs', lines 66:4-74:5
    Visibility: public -/
def queue.JobQueue.start
  (self : queue.JobQueue) :
  Result ((core.result.Result Unit queue.QueueError) × queue.JobQueue)
  := do
  if self.queued = 0#u32
  then ok (core.result.Result.Err queue.QueueError.NotStartable, self)
  else
    if self.running
    then ok (core.result.Result.Err queue.QueueError.NotStartable, self)
    else
      let i ← self.queued - 1#u32
      ok (core.result.Result.Ok (),
        { self with queued := i, running := true, attempts := 1#u32 })

/-- [jobq::queue::{jobq::queue::JobQueue}::complete]:
    Source: 'src/queue.rs', lines 77:4-85:5
    Visibility: public -/
def queue.JobQueue.complete
  (self : queue.JobQueue) :
  Result ((core.result.Result Unit queue.QueueError) × queue.JobQueue)
  := do
  if self.running
  then
    let i ← self.done + 1#u32
    ok (core.result.Result.Ok (),
      { self with running := false, attempts := 0#u32, done := i })
  else ok (core.result.Result.Err queue.QueueError.NotRunning, self)

/-- [jobq::queue::{jobq::queue::JobQueue}::fail]:
    Source: 'src/queue.rs', lines 89:4-102:5
    Visibility: public -/
def queue.JobQueue.fail
  (self : queue.JobQueue) :
  Result ((core.result.Result queue.FailOutcome queue.QueueError) ×
    queue.JobQueue)
  := do
  if self.running
  then
    if self.attempts < queue.MAX_ATTEMPTS
    then
      let i ← self.attempts + 1#u32
      ok (core.result.Result.Ok queue.FailOutcome.Retrying,
        { self with attempts := i })
    else
      let i ← self.failed + 1#u32
      ok (core.result.Result.Ok queue.FailOutcome.Exhausted,
        { self with running := false, attempts := 0#u32, failed := i })
  else ok (core.result.Result.Err queue.QueueError.NotRunning, self)

/-- [jobq::queue::{jobq::queue::JobQueue}::queued]:
    Source: 'src/queue.rs', lines 104:4-106:5
    Visibility: public -/
def queue.JobQueue.impl.queued (self : queue.JobQueue) : Result Std.U32 := do
  ok self.queued

/-- [jobq::queue::{jobq::queue::JobQueue}::is_running]:
    Source: 'src/queue.rs', lines 108:4-110:5
    Visibility: public -/
def queue.JobQueue.is_running (self : queue.JobQueue) : Result Bool := do
  ok self.running

/-- [jobq::queue::{jobq::queue::JobQueue}::attempts]:
    Source: 'src/queue.rs', lines 112:4-114:5
    Visibility: public -/
def queue.JobQueue.impl.attempts (self : queue.JobQueue) : Result Std.U32 := do
  ok self.attempts

/-- [jobq::queue::{jobq::queue::JobQueue}::done]:
    Source: 'src/queue.rs', lines 116:4-118:5
    Visibility: public -/
def queue.JobQueue.impl.done (self : queue.JobQueue) : Result Std.U32 := do
  ok self.done

/-- [jobq::queue::{jobq::queue::JobQueue}::failed]:
    Source: 'src/queue.rs', lines 120:4-122:5
    Visibility: public -/
def queue.JobQueue.impl.failed (self : queue.JobQueue) : Result Std.U32 := do
  ok self.failed

/-- [jobq::queue::{jobq::queue::JobQueue}::submitted]:
    Source: 'src/queue.rs', lines 124:4-126:5
    Visibility: public -/
def queue.JobQueue.impl.submitted
  (self : queue.JobQueue) : Result Std.U32 := do
  ok self.submitted

/-- [jobq::queue::{jobq::queue::JobQueue}::conserved]:
    Source: 'src/queue.rs', lines 129:4-132:5
    Visibility: public -/
def queue.JobQueue.conserved (self : queue.JobQueue) : Result Bool := do
  let in_flight ← lift (core.convert.num.FromU32Bool.from self.running)
  let i ← self.queued + in_flight
  let i1 ← i + self.done
  let i2 ← i1 + self.failed
  ok (i2 = self.submitted)

end jobq
